
//TERMINAL
export const SHOW_ALERT = 'TERMINAL/SHOW_ALERT';
export const HIDE_ALERT = 'TERMINAL/HIDE_ALERT';
export const SET_SYMBOL = 'TERMINAL/SET_SYMBOL';

//BOOK
export const REQUEST_BOOK = 'BOOK/REQUEST_BOOK';
export const FETCH_BOOK = 'BOOK/FETCH_BOOK';
export const SHOW_BOOK_LOADER = 'BOOK/SHOW_BOOK_LOADER';
export const HIDE_BOOK_LOADER = 'BOOK/HIDE_BOOK_LOADER';


//STATISTICS
export const FETCH_STATISTIC = 'STATISTICS/FETCH_STATISTIC';
export const REQUEST_STATISTIC = 'STATISTICS/REQUEST_STATISTIC';
export const HIDE_STATS_LOADER = 'STATISTICS/HIDE_STATS_LOADER';
export const SHOW_STATS_LOADER = 'STATISTICS/SHOW_STATS_LOADER';


//SYMBOLS
export const FETCH_SYMBOLS = 'SYMBOLS/FETCH_SYMBOLS';
export const REQUEST_SYMBOLS = 'SYMBOLS/REQUEST_SYMBOLS';
export const HIDE_SYMBOLS_LOADER = 'SYMBOLS/HIDE_SYMBOLS_LOADER';
export const SHOW_SYMBOLS_LOADER = 'SYMBOLS/SHOW_SYMBOLS_LOADER';

export const FETCH_CHART = 'CHART/FETCH_CHART';
export const REQUEST_CHART = 'CHART/REQUEST_CHART';
export const SHOW_CHART_LOADER = 'CHART/SHOW_CHART_LOADER';
export const HIDE_CHART_LOADER = 'CHART/HIDE_CHART_LOADER';



//BUY FORM

export const BUY_SET_PRICE = 'BUY_FORM/SET_PRICE';
export const BUY_SET_AMOUNT = 'BUY_FORM/SET_AMOUNT';
export const BUY_SET_TOTAL = 'BUY_FORM/SET_TOTAL';